name: Check for version tag on PR merge
run-name: Check for version tag on PR merge

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-merged-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for version tag
        run: ./compver.sh
