name: Post Merge Action
run-name: Post Merge Action

on:
  push:
    branches:
      - 'develop'

jobs:
  post-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global user.email "you@example.com" && git config --global user.name "Version Auto-Incrementer"

      - name: Run post-merge script
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./post_merge.sh
